[package]
name = "eventlog-sqlite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[dependencies]
eventlog-core.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
time.workspace = true
tokio = { workspace = true, features = ["rt"] }

[dev-dependencies]
rusqlite.workspace = true
eventlog-conformance.workspace = true
serde.workspace = true
time.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
